import * as fs from 'fs';
import * as path from 'path';
import { diffLines } from 'diff';
import type { MigrationConfig } from './config';

/**
 * Resolve migration filename based on naming config
 */
function resolveMigrationFilename(
  migrationDir: string,
  description: string,
  naming: MigrationConfig['naming'] = 'timestamp'
): string {
  if (naming === 'sequential') {
    // Find max NNN from existing files
    let max = 0;
    if (fs.existsSync(migrationDir)) {
      for (const f of fs.readdirSync(migrationDir)) {
        const m = f.match(/^(\d+)_/);
        if (m) max = Math.max(max, parseInt(m[1], 10));
      }
    }
    const next = String(max + 1).padStart(3, '0');
    return `${next}_${description}.sql`;
  }

  // Default: timestamp
  const ts = new Date().toISOString()
    .replace(/[-:]/g, '')
    .replace(/\..+/, '')
    .replace('T', '');
  return `${ts}_${description}.sql`;
}

/**
 * Generate ALTER TABLE statements from DDL diff
 */
function generateAlterStatements(tableName: string, fromDdl: string, toDdl: string): string[] {
  const statements: string[] = [];
  const diff = diffLines(fromDdl, toDdl);
  
  // Debug output removed - simple display
  
  // For column rename detection
  const removedColumns: Array<{name: string, definition: string}> = [];
  const addedColumns: Array<{name: string, definition: string}> = [];
  
  for (const part of diff) {
    if (part.added) {
      // Convert added lines to ALTER TABLE
      const lines = part.value.split('\n').filter(line => line.trim());
      for (const line of lines) {
        const trimmed = line.trim();
        
        // Detect column definition addition
        if (trimmed.includes('  ') && !trimmed.startsWith('CREATE') && !trimmed.startsWith('PRIMARY') && !trimmed.startsWith('CONSTRAINT')) {
          const columnDef = trimmed.replace(/,$/, '').trim();
          const columnMatch = columnDef.match(/^(\w+)\s+(.+)$/);
          if (columnMatch) {
            const columnName = columnMatch[1];
            const columnType = columnMatch[2];
            addedColumns.push({ name: columnName, definition: columnType });
          }
        }
      }
    } else if (part.removed) {
      // Convert removed lines to ALTER TABLE  
      const lines = part.value.split('\n').filter(line => line.trim());
      for (const line of lines) {
        const trimmed = line.trim();
        
        // Detect column definition removal
        if (trimmed.includes('  ') && !trimmed.startsWith('CREATE') && !trimmed.startsWith('PRIMARY') && !trimmed.startsWith('CONSTRAINT')) {
          const columnDef = trimmed.replace(/,$/, '').trim();
          const columnMatch = columnDef.match(/^(\w+)\s+(.+)$/);
          if (columnMatch) {
            const columnName = columnMatch[1];
            const columnType = columnMatch[2];
            removedColumns.push({ name: columnName, definition: columnType });
          }
        }
      }
    }
  }
  
  // Column rename detection (same type, different name)
  const renames: Array<{from: string, to: string}> = [];
  
  for (const removed of removedColumns) {
    const matching = addedColumns.find(added => added.definition === removed.definition);
    if (matching) {
      renames.push({ from: removed.name, to: matching.name });
      // Mark as processed
      removedColumns.splice(removedColumns.indexOf(removed), 1);
      addedColumns.splice(addedColumns.indexOf(matching), 1);
    }
  }
  
  // Debug log removed - simple display
  
  // Generate RENAME COLUMN statements
  for (const rename of renames) {
    statements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${rename.from} TO ${rename.to};`);
  }
  
  // Remaining removed columns
  for (const removed of removedColumns) {
    statements.push(`ALTER TABLE ${tableName} DROP COLUMN ${removed.name};`);
  }
  
  // Remaining added columns
  for (const added of addedColumns) {
    statements.push(`ALTER TABLE ${tableName} ADD COLUMN ${added.name} ${added.definition};`);
  }
  
  return statements;
}

/**
 * Generate migration file
 */
export async function generateMigrationFile(
  tableName: string,
  fromDdl: string,
  toDdl: string,
  projectDir: string = '.',
  migrationConfig?: MigrationConfig
): Promise<string | null> {
  const migrationDir = path.join(projectDir, migrationConfig?.dir ?? 'supabase/migrations');

  // Create migrations directory
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  // Generate ALTER TABLE statements
  const alterStatements = generateAlterStatements(tableName, fromDdl, toDdl);

  if (alterStatements.length === 0) {
    return await generateManualMigrationTemplate(tableName, fromDdl, toDdl, projectDir, migrationConfig);
  }

  const filename = resolveMigrationFilename(migrationDir, `update_${tableName}`, migrationConfig?.naming);
  const filepath = path.join(migrationDir, filename);
  
  // Build migration file content
  const content = `-- Migration generated by supatool
-- Table: ${tableName}
-- Generated at: ${new Date().toISOString()}

${alterStatements.join('\n')}
`;
  
  // Write file
  fs.writeFileSync(filepath, content, 'utf-8');
  
  console.log(`Migration file generated: ${filename}`);
  
  return filepath;
}

/**
 * Extract column definitions from DDL
 */
function extractColumns(ddl: string): Array<{name: string, definition: string}> {
  const columns: Array<{name: string, definition: string}> = [];
  
  // Extract CREATE TABLE part
  const createTableMatch = ddl.match(/CREATE TABLE[^(]*\((.*)\);?/is);
  if (!createTableMatch) {
    return columns;
  }
  
  const tableContent = createTableMatch[1];
  
  // Split column definitions and CONSTRAINTs
  const parts = tableContent.split(',').map(part => part.trim());
  
  for (const part of parts) {
    // Exclude CONSTRAINT, PRIMARY KEY
    if (part.match(/^(PRIMARY|CONSTRAINT|UNIQUE|FOREIGN|CHECK)/i)) {
      continue;
    }
    
    // Split column name and data type
    const columnMatch = part.trim().match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s+(.+)$/);
    if (columnMatch) {
      const columnName = columnMatch[1];
      const columnType = columnMatch[2];
      columns.push({ name: columnName, definition: columnType });
    }
  }
  
  return columns;
}

/**
 * Analyze column changes from diff
 */
function analyzeDiffForTemplate(fromDdl: string, toDdl: string): {
  removedColumns: Array<{name: string, definition: string}>;
  addedColumns: Array<{name: string, definition: string}>;
} {
  // Extract columns from each DDL
  const fromColumns = extractColumns(fromDdl);
  const toColumns = extractColumns(toDdl);
  
  // Removed columns (in FROM but not in TO)
  const removedColumns = fromColumns.filter(fromCol => 
    !toColumns.some(toCol => toCol.name === fromCol.name)
  );
  
  // Added columns (in TO but not in FROM)
  const addedColumns = toColumns.filter(toCol => 
    !fromColumns.some(fromCol => fromCol.name === toCol.name)
  );
  
  return { removedColumns, addedColumns };
}

/**
 * Generate manual migration template
 */
async function generateManualMigrationTemplate(
  tableName: string,
  fromDdl: string,
  toDdl: string,
  projectDir: string,
  migrationConfig?: MigrationConfig
): Promise<string | null> {
  const migrationDir = path.join(projectDir, migrationConfig?.dir ?? 'supabase/migrations');

  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  // Analyze diff
  const { removedColumns, addedColumns } = analyzeDiffForTemplate(fromDdl, toDdl);

  const filename = resolveMigrationFilename(migrationDir, `manual_update_${tableName}`, migrationConfig?.naming);
  const filepath = path.join(migrationDir, filename);
  
  // Build template from actual changes
  let migrationStatements: string[] = [];
  
  // Detect possible column renames
  const potentialRenames: Array<{from: string, to: string, definition: string}> = [];
  
  for (const removed of removedColumns) {
    const matching = addedColumns.find(added => added.definition === removed.definition);
    if (matching) {
      potentialRenames.push({ 
        from: removed.name, 
        to: matching.name,
        definition: removed.definition
      });
    }
  }
  
  // Remaining removals and additions
  const remainingRemoved = removedColumns.filter(r => 
    !potentialRenames.some(p => p.from === r.name)
  );
  const remainingAdded = addedColumns.filter(a => 
    !potentialRenames.some(p => p.to === a.name)
  );
  
  // Generate template statements (DROP -> ADD -> RENAME order)
  if (remainingRemoved.length > 0) {
    migrationStatements.push('-- Column removals:');
    for (const removed of remainingRemoved) {
      migrationStatements.push(`ALTER TABLE ${tableName} DROP COLUMN ${removed.name};`);
    }
  }
  
  if (remainingAdded.length > 0) {
    if (migrationStatements.length > 0) migrationStatements.push('');
    migrationStatements.push('-- Column additions:');
    for (const added of remainingAdded) {
      migrationStatements.push(`ALTER TABLE ${tableName} ADD COLUMN ${added.name} ${added.definition};`);
    }
  }
  
  if (potentialRenames.length > 0) {
    if (migrationStatements.length > 0) migrationStatements.push('');
    migrationStatements.push('-- Possible column renames:');
    for (const rename of potentialRenames) {
      migrationStatements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${rename.from} TO ${rename.to};`);
    }
  }
  
  // Fallback when nothing detected
  if (migrationStatements.length === 0) {
    migrationStatements = [
      `-- Manual migration for ${tableName}`,
      `-- No specific changes detected, please edit manually`,
      ``,
      `-- ALTER TABLE ${tableName} RENAME COLUMN old_name TO new_name;`,
      `-- ALTER TABLE ${tableName} ADD COLUMN new_column TYPE;`,
      `-- ALTER TABLE ${tableName} DROP COLUMN old_column;`
    ];
  }
  
  const content = `-- Manual migration for ${tableName}
-- Edit this file and apply manually or using supabase CLI

${migrationStatements.join('\n')}
`;
  
  fs.writeFileSync(filepath, content, 'utf-8');
  
  console.log(`Manual migration template generated: ${filename}`);
  
  return filepath;
}

/**
 * Generate a RENAME TABLE migration when a table appears renamed.
 * (old exists on remote, new exists on local, columns are highly similar)
 */
export async function generateRenameTableMigrationFile(
  schema: string,
  oldName: string,
  newName: string,
  projectDir: string = '.',
  migrationConfig?: MigrationConfig
): Promise<string> {
  const migrationDir = path.join(projectDir, migrationConfig?.dir ?? 'supabase/migrations');
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  const filename = resolveMigrationFilename(
    migrationDir,
    `rename_${schema}_${oldName}_to_${newName}`,
    migrationConfig?.naming
  );
  const filepath = path.join(migrationDir, filename);

  const content = `-- Migration generated by supatool
-- Rename table: ${schema}.${oldName} → ${schema}.${newName}
-- Generated at: ${new Date().toISOString()}
-- WARNING: Review carefully before applying. supatool detected this as a rename
--          based on column similarity, but it may be an unrelated add/drop pair.

ALTER TABLE ${schema === 'public' ? '' : schema + '.'}${oldName} RENAME TO ${newName};
`;

  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`Rename migration generated: ${filename}`);
  return filepath;
}

/**
 * Normalize function DDL for comparison (strip supatool header comment, trailing whitespace)
 */
function normalizeFunctionDdl(ddl: string): string {
  return ddl
    .split('\n')
    .filter(line => !line.startsWith('-- Generated by supatool'))
    .join('\n')
    .replace(/\s+$/, '')
    .trim();
}

/**
 * Generate a migration file for a changed function.
 * localDdl is used as-is (must be valid CREATE OR REPLACE FUNCTION DDL).
 */
export async function generateFunctionMigrationFile(
  schema: string,
  funcName: string,
  localDdl: string,
  remoteDdl: string,
  projectDir: string = '.',
  migrationConfig?: MigrationConfig
): Promise<string | null> {
  const normalizedLocal = normalizeFunctionDdl(localDdl);
  const normalizedRemote = normalizeFunctionDdl(remoteDdl);

  if (normalizedLocal === normalizedRemote) return null;

  const migrationDir = path.join(projectDir, migrationConfig?.dir ?? 'supabase/migrations');
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  const filename = resolveMigrationFilename(migrationDir, `update_fn_${schema}_${funcName}`, migrationConfig?.naming);
  const filepath = path.join(migrationDir, filename);

  const content = `-- Migration generated by supatool
-- Function: ${schema}.${funcName}
-- Generated at: ${new Date().toISOString()}

${normalizedLocal.endsWith(';') ? normalizedLocal : normalizedLocal + ';'}
`;

  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`Function migration generated: ${filename}`);
  return filepath;
}

// ---------------------------------------------------------------------------
// RLS policy migration (DROP + CREATE)
// ---------------------------------------------------------------------------

export interface RlsPolicy {
  policyName: string;
  tableName: string;  // schema-qualified e.g. public.users
  cmd: string;        // SELECT | INSERT | UPDATE | DELETE | ALL
  roles: string;      // e.g. authenticated, anon
  qual: string | null;     // USING expression
  withCheck: string | null; // WITH CHECK expression
  permissive: boolean;
}

/**
 * Generate DROP POLICY IF EXISTS + CREATE POLICY statements for changed policies.
 */
export async function generateRlsMigrationFile(
  changedPolicies: RlsPolicy[],
  droppedPolicies: { policyName: string; tableName: string }[],
  projectDir: string = '.',
  migrationConfig?: MigrationConfig
): Promise<string | null> {
  if (changedPolicies.length === 0 && droppedPolicies.length === 0) return null;

  const migrationDir = path.join(projectDir, migrationConfig?.dir ?? 'supabase/migrations');
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  const statements: string[] = [];

  for (const p of droppedPolicies) {
    statements.push(`DROP POLICY IF EXISTS "${p.policyName}" ON ${p.tableName};`);
  }

  for (const p of changedPolicies) {
    statements.push(`DROP POLICY IF EXISTS "${p.policyName}" ON ${p.tableName};`);
    const permissive = p.permissive ? 'PERMISSIVE' : 'RESTRICTIVE';
    const roles = p.roles || 'public';
    let sql = `CREATE POLICY "${p.policyName}" ON ${p.tableName}\n` +
      `  AS ${permissive} FOR ${p.cmd} TO ${roles}`;
    if (p.qual) sql += `\n  USING (${p.qual})`;
    if (p.withCheck) sql += `\n  WITH CHECK (${p.withCheck})`;
    sql += ';';
    statements.push(sql);
  }

  const filename = resolveMigrationFilename(migrationDir, 'update_rls', migrationConfig?.naming);
  const filepath = path.join(migrationDir, filename);
  const content = `-- Migration generated by supatool
-- RLS policies: ${changedPolicies.length} changed, ${droppedPolicies.length} dropped
-- Generated at: ${new Date().toISOString()}

${statements.join('\n\n')}
`;

  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`RLS migration generated: ${filename}`);
  return filepath;
}