import * as fs from 'fs';
import * as path from 'path';
import { diffLines } from 'diff';

/**
 * Generate ALTER TABLE statements from DDL diff
 */
function generateAlterStatements(tableName: string, fromDdl: string, toDdl: string): string[] {
  const statements: string[] = [];
  const diff = diffLines(fromDdl, toDdl);
  
  // Debug output removed - simple display
  
  // For column rename detection
  const removedColumns: Array<{name: string, definition: string}> = [];
  const addedColumns: Array<{name: string, definition: string}> = [];
  
  for (const part of diff) {
    if (part.added) {
      // Convert added lines to ALTER TABLE
      const lines = part.value.split('\n').filter(line => line.trim());
      for (const line of lines) {
        const trimmed = line.trim();
        
        // Detect column definition addition
        if (trimmed.includes('  ') && !trimmed.startsWith('CREATE') && !trimmed.startsWith('PRIMARY') && !trimmed.startsWith('CONSTRAINT')) {
          const columnDef = trimmed.replace(/,$/, '').trim();
          const columnMatch = columnDef.match(/^(\w+)\s+(.+)$/);
          if (columnMatch) {
            const columnName = columnMatch[1];
            const columnType = columnMatch[2];
            addedColumns.push({ name: columnName, definition: columnType });
          }
        }
      }
    } else if (part.removed) {
      // Convert removed lines to ALTER TABLE  
      const lines = part.value.split('\n').filter(line => line.trim());
      for (const line of lines) {
        const trimmed = line.trim();
        
        // Detect column definition removal
        if (trimmed.includes('  ') && !trimmed.startsWith('CREATE') && !trimmed.startsWith('PRIMARY') && !trimmed.startsWith('CONSTRAINT')) {
          const columnDef = trimmed.replace(/,$/, '').trim();
          const columnMatch = columnDef.match(/^(\w+)\s+(.+)$/);
          if (columnMatch) {
            const columnName = columnMatch[1];
            const columnType = columnMatch[2];
            removedColumns.push({ name: columnName, definition: columnType });
          }
        }
      }
    }
  }
  
  // Column rename detection (same type, different name)
  const renames: Array<{from: string, to: string}> = [];
  
  for (const removed of removedColumns) {
    const matching = addedColumns.find(added => added.definition === removed.definition);
    if (matching) {
      renames.push({ from: removed.name, to: matching.name });
      // Mark as processed
      removedColumns.splice(removedColumns.indexOf(removed), 1);
      addedColumns.splice(addedColumns.indexOf(matching), 1);
    }
  }
  
  // Debug log removed - simple display
  
  // Generate RENAME COLUMN statements
  for (const rename of renames) {
    statements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${rename.from} TO ${rename.to};`);
  }
  
  // Remaining removed columns
  for (const removed of removedColumns) {
    statements.push(`ALTER TABLE ${tableName} DROP COLUMN ${removed.name};`);
  }
  
  // Remaining added columns
  for (const added of addedColumns) {
    statements.push(`ALTER TABLE ${tableName} ADD COLUMN ${added.name} ${added.definition};`);
  }
  
  return statements;
}

/**
 * Generate migration file
 */
export async function generateMigrationFile(
  tableName: string, 
  fromDdl: string, 
  toDdl: string,
  projectDir: string = '.'
): Promise<string | null> {
  const migrationDir = path.join(projectDir, 'supabase', 'migrations');
  
  // Create migrations directory
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }
  
  // Generate ALTER TABLE statements
  const alterStatements = generateAlterStatements(tableName, fromDdl, toDdl);
  
  if (alterStatements.length === 0) {
    return await generateManualMigrationTemplate(tableName, fromDdl, toDdl, projectDir);
  }
  
  // Generate filename from timestamp
  const now = new Date();
  const timestamp = now.toISOString()
    .replace(/[-:]/g, '')
    .replace(/\..+/, '')
    .replace('T', '');
  
  const filename = `${timestamp}_update_${tableName}.sql`;
  const filepath = path.join(migrationDir, filename);
  
  // Build migration file content
  const content = `-- Migration generated by supatool
-- Table: ${tableName}
-- Generated at: ${now.toISOString()}

${alterStatements.join('\n')}
`;
  
  // Write file
  fs.writeFileSync(filepath, content, 'utf-8');
  
  console.log(`Migration file generated: ${filename}`);
  
  return filepath;
}

/**
 * Extract column definitions from DDL
 */
function extractColumns(ddl: string): Array<{name: string, definition: string}> {
  const columns: Array<{name: string, definition: string}> = [];
  
  // Extract CREATE TABLE part
  const createTableMatch = ddl.match(/CREATE TABLE[^(]*\((.*)\);?/is);
  if (!createTableMatch) {
    return columns;
  }
  
  const tableContent = createTableMatch[1];
  
  // Split column definitions and CONSTRAINTs
  const parts = tableContent.split(',').map(part => part.trim());
  
  for (const part of parts) {
    // Exclude CONSTRAINT, PRIMARY KEY
    if (part.match(/^(PRIMARY|CONSTRAINT|UNIQUE|FOREIGN|CHECK)/i)) {
      continue;
    }
    
    // Split column name and data type
    const columnMatch = part.trim().match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s+(.+)$/);
    if (columnMatch) {
      const columnName = columnMatch[1];
      const columnType = columnMatch[2];
      columns.push({ name: columnName, definition: columnType });
    }
  }
  
  return columns;
}

/**
 * Analyze column changes from diff
 */
function analyzeDiffForTemplate(fromDdl: string, toDdl: string): {
  removedColumns: Array<{name: string, definition: string}>;
  addedColumns: Array<{name: string, definition: string}>;
} {
  // Extract columns from each DDL
  const fromColumns = extractColumns(fromDdl);
  const toColumns = extractColumns(toDdl);
  
  // Removed columns (in FROM but not in TO)
  const removedColumns = fromColumns.filter(fromCol => 
    !toColumns.some(toCol => toCol.name === fromCol.name)
  );
  
  // Added columns (in TO but not in FROM)
  const addedColumns = toColumns.filter(toCol => 
    !fromColumns.some(fromCol => fromCol.name === toCol.name)
  );
  
  return { removedColumns, addedColumns };
}

/**
 * Generate manual migration template
 */
async function generateManualMigrationTemplate(
  tableName: string,
  fromDdl: string,
  toDdl: string,
  projectDir: string
): Promise<string | null> {
  const migrationDir = path.join(projectDir, 'supabase', 'migrations');
  
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }
  
  // Analyze diff
  const { removedColumns, addedColumns } = analyzeDiffForTemplate(fromDdl, toDdl);
  
  // Generate filename from timestamp
  const now = new Date();
  const timestamp = now.toISOString()
    .replace(/[-:]/g, '')
    .replace(/\..+/, '')
    .replace('T', '');
  
  const filename = `${timestamp}_manual_update_${tableName}.sql`;
  const filepath = path.join(migrationDir, filename);
  
  // Build template from actual changes
  let migrationStatements: string[] = [];
  
  // Detect possible column renames
  const potentialRenames: Array<{from: string, to: string, definition: string}> = [];
  
  for (const removed of removedColumns) {
    const matching = addedColumns.find(added => added.definition === removed.definition);
    if (matching) {
      potentialRenames.push({ 
        from: removed.name, 
        to: matching.name,
        definition: removed.definition
      });
    }
  }
  
  // Remaining removals and additions
  const remainingRemoved = removedColumns.filter(r => 
    !potentialRenames.some(p => p.from === r.name)
  );
  const remainingAdded = addedColumns.filter(a => 
    !potentialRenames.some(p => p.to === a.name)
  );
  
  // Generate template statements (DROP -> ADD -> RENAME order)
  if (remainingRemoved.length > 0) {
    migrationStatements.push('-- Column removals:');
    for (const removed of remainingRemoved) {
      migrationStatements.push(`ALTER TABLE ${tableName} DROP COLUMN ${removed.name};`);
    }
  }
  
  if (remainingAdded.length > 0) {
    if (migrationStatements.length > 0) migrationStatements.push('');
    migrationStatements.push('-- Column additions:');
    for (const added of remainingAdded) {
      migrationStatements.push(`ALTER TABLE ${tableName} ADD COLUMN ${added.name} ${added.definition};`);
    }
  }
  
  if (potentialRenames.length > 0) {
    if (migrationStatements.length > 0) migrationStatements.push('');
    migrationStatements.push('-- Possible column renames:');
    for (const rename of potentialRenames) {
      migrationStatements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${rename.from} TO ${rename.to};`);
    }
  }
  
  // Fallback when nothing detected
  if (migrationStatements.length === 0) {
    migrationStatements = [
      `-- Manual migration for ${tableName}`,
      `-- No specific changes detected, please edit manually`,
      ``,
      `-- ALTER TABLE ${tableName} RENAME COLUMN old_name TO new_name;`,
      `-- ALTER TABLE ${tableName} ADD COLUMN new_column TYPE;`,
      `-- ALTER TABLE ${tableName} DROP COLUMN old_column;`
    ];
  }
  
  const content = `-- Manual migration for ${tableName}
-- Edit this file and apply manually or using supabase CLI

${migrationStatements.join('\n')}
`;
  
  fs.writeFileSync(filepath, content, 'utf-8');
  
  console.log(`Manual migration template generated: ${filename}`);
  
  return filepath;
}

/**
 * Advanced diff analysis (detect column changes)
 */
function analyzeColumnChanges(tableName: string, localDdl: string, remoteDdl: string): string[] {
  const statements: string[] = [];
  
  // Simple case: detect column name change
  const localLines = localDdl.split('\n').map(line => line.trim()).filter(line => line);
  const remoteLines = remoteDdl.split('\n').map(line => line.trim()).filter(line => line);
  
  // Advanced detection (type change, default change) to be implemented later
  // Currently only basic add/remove
  
  return statements;
} 