import { Client } from 'pg';
import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

interface SeedGenOptions {
  connectionString: string;
  tablesYamlPath: string;
  outputDir: string;
}

/**
 * Parse tables.yaml into { schema -> table[] } map.
 * Format:
 *   public:
 *     - users
 *     - posts
 *   admin:
 *     - platforms
 */
function parseTablesYaml(yamlPath: string): { schema: string; table: string }[] {
  const yamlObj = yaml.load(fs.readFileSync(yamlPath, 'utf8')) as any;
  if (!yamlObj || typeof yamlObj !== 'object' || Array.isArray(yamlObj)) {
    throw new Error(
      'Invalid tables.yaml format. Use schema-grouped format:\n  public:\n    - users\n  admin:\n    - platforms'
    );
  }

  // Detect old format: top-level "tables:" key with array value
  if ('tables' in yamlObj && Array.isArray(yamlObj.tables)) {
    throw new Error(
      'Outdated tables.yaml format detected.\n\n' +
      'Migrate to schema-grouped format:\n\n' +
      '  Before:          After:\n' +
      '  tables:          public:\n' +
      '    - users    →     - users\n' +
      '    - posts          - posts\n' +
      '    - admin.x      admin:\n' +
      '                     - x\n'
    );
  }

  const entries: { schema: string; table: string }[] = [];
  for (const [schema, tables] of Object.entries(yamlObj)) {
    if (!Array.isArray(tables)) {
      throw new Error(`tables.yaml: value of "${schema}" must be a list of table names`);
    }
    for (const table of tables as string[]) {
      // Detect dot notation inside a schema group
      if (table.includes('.')) {
        throw new Error(
          `tables.yaml: "${table}" under "${schema}" uses dot notation.\n` +
          `Use schema-grouped format instead:\n` +
          `  ${table.split('.')[0]}:\n` +
          `    - ${table.split('.')[1]}`
        );
      }
      entries.push({ schema, table });
    }
  }
  return entries;
}

/**
 * Fetch table data from remote DB and generate AI seed JSON
 * @param options SeedGenOptions
 */
export async function generateSeedsFromRemote(options: SeedGenOptions): Promise<void> {
  const tables = parseTablesYaml(options.tablesYamlPath);

  // Generate datetime subdir name (e.g. 20250705_1116_supatool)
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const mm = String(now.getMinutes()).padStart(2, '0');
  const folderName = `${y}${m}${d}_${hh}${mm}_supatool`;
  const outDir = path.join(options.outputDir, folderName);

  // DB connection
  const client = new Client({ connectionString: options.connectionString });
  await client.connect();

  const processedFiles: { schema: string; table: string; fileName: string; rowCount: number }[] = [];

  for (const { schema, table } of tables) {
    // Create schema subdir
    const schemaDir = path.join(outDir, schema);
    if (!fs.existsSync(schemaDir)) {
      fs.mkdirSync(schemaDir, { recursive: true });
    }
    // Fetch data
    const res = await client.query(`SELECT * FROM "${schema}"."${table}"`);
    const rows = res.rows;
    // Output JSON
    const fileName = `${table}_seed.json`;
    const filePath = path.join(schemaDir, fileName);
    const json = {
      table: `${schema}.${table}`,
      fetched_at: now.toISOString(),
      fetched_by: 'supatool',
      note: 'This data is a snapshot of the remote DB at the above time. For AI coding reference. You can update it by running the update command again.',
      rows
    };
    fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
    processedFiles.push({ schema, table, fileName, rowCount: rows.length });
  }

  await client.end();

  // llms.txt index (schema/file paths, overwrite each run)
  let llmsTxt = `# AI seed data index (generated by supatool)\n`;
  llmsTxt += `# fetched_at: ${now.toISOString()}\n`;
  llmsTxt += `# folder: ${folderName}\n`;
  llmsTxt += `# Schema catalog: ../schemas/llms.txt\n`;
  for (const { schema, table, fileName, rowCount } of processedFiles) {
    let tableComment = '';
    try {
      const commentRes = await getTableComment(options.connectionString, schema, table);
      if (commentRes) tableComment = commentRes;
    } catch {}
    llmsTxt += `${schema}.${table}: ${schema}/${fileName} (${rowCount} rows)`;
    if (tableComment) llmsTxt += ` # ${tableComment}`;
    llmsTxt += `\n`;
  }
  const llmsPath = path.join(options.outputDir, 'llms.txt');
  fs.writeFileSync(llmsPath, llmsTxt, 'utf8');

  console.log(`Seed export completed. Processed tables: ${processedFiles.length}`);
  console.log(`llms.txt index written to: ${llmsPath}`);
}

/** Utility to get table comment */
async function getTableComment(connectionString: string, schema: string, table: string): Promise<string | null> {
  const client = new Client({ connectionString });
  await client.connect();
  try {
    const res = await client.query(
      `SELECT obj_description(c.oid) as comment FROM pg_class c JOIN pg_namespace n ON c.relnamespace = n.oid WHERE c.relname = $1 AND n.nspname = $2 AND c.relkind = 'r'`,
      [table, schema]
    );
    if (res.rows.length > 0 && res.rows[0].comment) {
      return res.rows[0].comment;
    }
    return null;
  } finally {
    await client.end();
  }
} 