import * as fs from 'fs';
import * as path from 'path';
import { askUserConfirmation } from './utils';

// Manage global "approve all" state
let globalApproveAll = false;

/**
 * Reset approve all mode
 */
export function resetApprovalState(): void {
  globalApproveAll = false;
}

/**
 * Move existing file to backup directory
 */
async function backupExistingFile(filePath: string, schemaDir: string, force: boolean = false): Promise<boolean> {
  if (!fs.existsSync(filePath)) {
    return true;
  }

  if (!force && !globalApproveAll) {
    const fileName = path.basename(filePath);
    const response = await askUserConfirmation(`↓ Overwrite existing file ${fileName}?`, {
      allowAll: true,
      message: '(y/N/a[all]): '
    });
    
    if (response === 'all') {
      globalApproveAll = true;
      console.log('✅ Approving all files');
    } else if (response === false) {
      console.log('Skipped');
      return false;
    }
  }

  const backupDir = path.join(schemaDir, 'backup');
  if (!fs.existsSync(backupDir)) {
    fs.mkdirSync(backupDir, { recursive: true });
  }

  const fileName = path.basename(filePath);
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupFileName = `${timestamp}_${fileName}`;
  const backupPath = path.join(backupDir, backupFileName);

  fs.renameSync(filePath, backupPath);
  console.log(`Existing file backed up: ${backupPath}`);
  return true;
}

/**
 * Move files for non-existent tables to backup
 */
export async function backupOrphanedFiles(schemaDir: string, existingTables: Set<string>, force: boolean = false): Promise<void> {
  if (!fs.existsSync(schemaDir)) {
    return;
  }

  const files = fs.readdirSync(schemaDir);
  const orphanedFiles: string[] = [];
  
  for (const file of files) {
    if (!file.endsWith('.sql')) continue;
    
    const tableName = path.basename(file, '.sql');
    if (!existingTables.has(tableName)) {
      orphanedFiles.push(file);
    }
  }

  if (orphanedFiles.length === 0) {
    return;
  }

  if (!force) {
    console.log('\nThe following files correspond to non-existent tables:');
    orphanedFiles.forEach(file => console.log(`  - ${file}`));
    
    const confirmed = await askUserConfirmation('Move these files to backup folder?');
    if (!confirmed) {
      console.log('Skipped moving orphaned files');
      return;
    }
  }

  for (const file of orphanedFiles) {
    const tableName = path.basename(file, '.sql');
    const filePath = path.join(schemaDir, file);
    console.log(`[${tableName}] Backing up file for non-existent table`);
    await backupExistingFile(filePath, schemaDir, true); // force=true since already confirmed
  }
}

/**
 * Write schema to file
 */
export async function writeSchemaToFile(
  ddl: string,
  schemaDir: string,
  timestamp: number,
  fileName: string,
  tableName: string,
  force: boolean = false
): Promise<boolean> {
  if (!fs.existsSync(schemaDir)) {
    fs.mkdirSync(schemaDir, { recursive: true });
  }

  const filePath = path.join(schemaDir, fileName);
  
  // Backup existing file if exists
  const canProceed = await backupExistingFile(filePath, schemaDir, force);
  if (!canProceed) {
    return false;
  }
  
  // Record remote database last updated time (metadata for comparison - do not edit)
  const remoteTimestamp = `-- Remote last updated: ${new Date(timestamp * 1000).toISOString()}\n`;
  // Sync execution time (reference info)
  const syncTimestamp = `-- Synced by supatool at: ${new Date().toISOString()}\n`;
  // Warning comment
  const warningComment = `-- ⚠️  This file is auto-generated by supatool. Manual edits may be lost during sync.\n`;
  const tableComment = `-- Table: ${tableName}\n\n`;
  const finalContent = remoteTimestamp + syncTimestamp + warningComment + tableComment + ddl;

  fs.writeFileSync(filePath, finalContent, 'utf-8');
  console.log(`📁 Saved to ${tableName}.sql`);
  
  return true;
}

/**
 * Move orphaned files to backup folder
 */
export function moveToBackup(schemaDir: string, fileName: string): void {
  const backupDir = path.join(schemaDir, 'backup');
  
  if (!fs.existsSync(backupDir)) {
    fs.mkdirSync(backupDir, { recursive: true });
  }

  const sourceFile = path.join(schemaDir, fileName);
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupFile = path.join(backupDir, `${path.basename(fileName, '.sql')}_${timestamp}.sql`);

  if (fs.existsSync(sourceFile)) {
    fs.renameSync(sourceFile, backupFile);
    console.log(`📦 Backed up ${fileName} to ${backupFile}`);
  }
} 