// Supabase CRUD operations for workspace_credit_logs
// This file is automatically generated. Do not edit it directly.
import { supabase } from "../client";
import { Tables, TablesInsert, TablesUpdate } from "@shared/types";

type workspace_credit_logs = Tables<'workspace_credit_logs'>;
type FilterTypesValue = string | number | boolean | null | Record<string, any>;
type Filters = Record<string, FilterTypesValue | FilterTypesValue[]>;

  // Function to apply filters to a query
function applyFilters(query: any, filters: Filters): any {
    for (const [key, value] of Object.entries(filters)) {
        if (Array.isArray(value)) {
            query = query.in(key, value); // Use 'in' for array values
        } else if (typeof value === 'object' && value !== null) {
            for (const [operator, val] of Object.entries(value)) {
                switch (operator) {
                    case 'eq':
                        query = query.eq(key, val);
                        break;
                    case 'neq':
                        query = query.neq(key, val);
                        break;
                    case 'like':
                        query = query.like(key, val);
                        break;
                    case 'ilike':
                        query = query.ilike(key, val);
                        break;
                    case 'lt':
                        query = query.lt(key, val);
                        break;
                    case 'lte':
                        query = query.lte(key, val);
                        break;
                    case 'gte':
                        query = query.gte(key, val);
                        break;
                    case 'gt':
                        query = query.gt(key, val);
                        break;
                    case 'contains':
                        query = query.contains(key, val);
                        break;
                    case 'contains_any':
                        query = query.contains_any(key, val);
                        break;
                    case 'contains_all':
                        query = query.contains_all(key, val);
                        break;
                    // Add more operators as needed
                    default:
                        throw new Error('Unsupported operator: ' + operator);
                }
            }
        } else {
            query = query.eq(key, value); // Default to 'eq' for simple values
        }
    }
    return query;
}

// Read multiple rows with dynamic filters
export async function selectWorkspaceCreditLogsRowsWithFilters({ filters }: { filters: Filters }): Promise<workspace_credit_logs[]> {
    if (!filters || typeof filters !== 'object') return [];
    try {
        let query = supabase.from('workspace_credit_logs').select('*');
        query = applyFilters(query, filters);

        const result = await query;
        
        if (result.error) {
            throw new Error(`Failed to fetch workspace_credit_logs: ${result.error.message}`);
        }
        
        return (result.data as unknown as workspace_credit_logs[]) || [];
    } catch (error) {
        console.error('Error in selectWorkspaceCreditLogsRowsWithFilters:', error);
        throw error;
    }
}

// Read a single row with dynamic filters
export async function selectWorkspaceCreditLogsSingleRowWithFilters({ filters }: { filters: Filters }): Promise<workspace_credit_logs | null> {
    if (!filters || typeof filters !== 'object') return null;
    try {
        let query = supabase.from('workspace_credit_logs').select('*');
        query = applyFilters(query, filters).single();

        const result = await query;
        
        if (result.error) {
            if (result.error.code === 'PGRST116') {
                return null;
            }
            throw new Error(`Failed to fetch workspace_credit_logs: ${result.error.message}`);
        }
        
        return result.data as unknown as workspace_credit_logs;
    } catch (error) {
        console.error('Error in selectWorkspaceCreditLogsSingleRowWithFilters:', error);
        throw error;
    }
}

// Read single row using id
export async function selectWorkspaceCreditLogsRowById({ id }: { id: string }): Promise<workspace_credit_logs | null> {
    if (!id) {
        throw new Error('ID is required');
    }
    try {
        const result = await supabase
            .from('workspace_credit_logs')
            .select('*')
            .eq('id', id)
            .single();
        
        if (result.error) {
            if (result.error.code === 'PGRST116') {
                return null;
            }
            throw new Error(`Failed to fetch workspace_credit_logs: ${result.error.message}`);
        }
        
        return result.data as workspace_credit_logs;
    } catch (error) {
        console.error('Error in selectWorkspaceCreditLogsRowById:', error);
        throw error;
    }
}

// Create Function
export async function insertWorkspaceCreditLogsRow({ data }: { data: TablesInsert<'workspace_credit_logs'> }): Promise<workspace_credit_logs> {
    if (!data) {
        throw new Error('Data is required for creation');
    }
    try {
        const result = await supabase
            .from('workspace_credit_logs')
            .insert([data])
            .select()
            .single();

        if (result.error) {
            throw new Error(`Failed to create workspace_credit_logs: ${result.error.message}`);
        }
        
        if (!result.data) {
            throw new Error('No data returned after creation');
        }
        
        return result.data as workspace_credit_logs;
    } catch (error) {
        console.error('Error in insertWorkspaceCreditLogsRow:', error);
        throw error;
    }
}

// Update Function
export async function updateWorkspaceCreditLogsRow({ id, data }: { id: string; data: TablesUpdate<'workspace_credit_logs'> }): Promise<workspace_credit_logs> {
    if (!id) {
        throw new Error('ID is required for update');
    }
    if (!data || Object.keys(data).length === 0) {
        throw new Error('Update data is required');
    }
    try {
        const result = await supabase
            .from('workspace_credit_logs')
            .update(data)
            .eq('id', id)
            .select()
            .single();
            
        if (result.error) {
            if (result.error.code === 'PGRST116') {
                throw new Error(`workspace_credit_logs with ID ${id} not found`);
            }
            throw new Error(`Failed to update workspace_credit_logs: ${result.error.message}`);
        }
        
        if (!result.data) {
            throw new Error(`workspace_credit_logs with ID ${id} not found`);
        }
        
        return result.data as workspace_credit_logs;
    } catch (error) {
        console.error('Error in updateWorkspaceCreditLogsRow:', error);
        throw error;
    }
}

// Delete Function
export async function deleteWorkspaceCreditLogsRow({ id }: { id: string }): Promise<boolean> {
    if (!id) {
        throw new Error('ID is required for deletion');
    }
    try {
        const result = await supabase
            .from('workspace_credit_logs')
            .delete()
            .eq('id', id);
            
        if (result.error) {
            throw new Error(`Failed to delete workspace_credit_logs: ${result.error.message}`);
        }
        
        return true;
    } catch (error) {
        console.error('Error in deleteWorkspaceCreditLogsRow:', error);
        throw error;
    }
}

// All functions are exported individually above
